## the script was generated by Gemini of google
#
"""
## 主な改善ポイント
- データロードの共通化: df = pd.read_csv(...) を __main__ 側で1回だけ実行し、各Fold処理には参照渡しで渡すため、I/Oオーバーヘッドが大幅に削減されます。

- 柔軟な実行形式: 単一Foldのデバッグ実行（--fold 0）と、全コアを使った一括並列実行（--fold なし）のどちらにも対応できます。
"""
import argparse
import os
import joblib
import pandas as pd
from sklearn import metrics
from sklearn import tree
import config

def run(fold, df):
    # CSV読み込みは外側で行い、df を渡すことで重複ロードを回避
    df_train = df[df.kfold != fold].reset_index(drop=True)
    df_valid = df[df.kfold == fold].reset_index(drop=True)

    x_train = df_train.drop("label", axis=1).values
    y_train = df_train.label.values

    x_valid = df_valid.drop("label", axis=1).values
    y_valid = df_valid.label.values

    clf = tree.DecisionTreeClassifier()
    clf.fit(x_train, y_train)

    preds = clf.predict(x_valid)
    accuracy = metrics.accuracy_score(y_valid, preds)
    print(f"Fold={fold}, Accuracy={accuracy:.4f}")

    # モデル保存用のディレクトリがなければ作成
    os.makedirs(config.MODEL_OUTPUT, exist_ok=True)
    joblib.dump(clf, os.path.join(config.MODEL_OUTPUT, f"dt_{fold}.bin"))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--fold", type=int, default=-1, help="実行するFold番号（未指定時は全Fold並列）")
    args = parser.parse_args()

    # データロードは一度だけ行う
    df = pd.read_csv(config.TRAINING_FILE)

    if args.fold != -1:
        # 単一Fold実行
        run(fold=args.fold, df=df)
    else:
        # 全Foldをjoblibで並列実行 (全コア使用)
        num_folds = df.kfold.nunique()
        joblib.Parallel(n_jobs=-1)(
            joblib.delayed(run)(fold=fold, df=df) for fold in range(num_folds)
        )
