[project]
name = "aaamlp-exp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.3",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "pyside6>=6.11.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "torch>=2.13.0",
    "transformers>=5.15.1",
]

[tool.basedpyright]
# extraPath : complimations from lsp.
extraPaths = [
    # "./ch01_03_basics/src",
    # "./ch01_03_basics/src/ch03_funcs",
    "./ch04_categorical/src",
    "."
]

[tool.pyrefly]
# earch-path: complimations from lsp
search-path = [
    # "./ch01_03_basics/src",
    # "./ch01_03_basics/src/ch03_funcs",
    "./ch04_categorical/src",
    "."
]
[tool.uv.workspace]
members = [
    "ch04_categorical",
    "ch01_03_basics",
    "ch05_images",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter-lsp>=2.3.1",
    "jupyterlab>=4.6.3",
    "jupyterlab-lsp>=5.3.0",
    "pandas-stubs>=3.0.5.260730",
    "pytest>=9.1.1",
]
